CREATE DATABASE IF NOT EXISTS limpacao;
USE limpacao;

CREATE TABLE IF NOT EXISTS usuarios (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  senha VARCHAR(255) NOT NULL,
  criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS relatorios (
  id INT AUTO_INCREMENT PRIMARY KEY,
  titulo VARCHAR(255) NOT NULL,
  localizacao VARCHAR(255) NOT NULL,
  urgencia VARCHAR(20) NOT NULL,
  status VARCHAR(30) NOT NULL,
  data DATE NOT NULL,
  imagem TEXT,
  descricao TEXT NOT NULL,
  autor VARCHAR(255) NOT NULL,
  participantes INT DEFAULT 0,
  ajudantes INT DEFAULT 0,
  multirao TINYINT(1) DEFAULT 0,
  status_anterior VARCHAR(30),
  usuario_id INT,
  criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  atualizado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS ofertas_ajuda (
  id INT AUTO_INCREMENT PRIMARY KEY,
  relatorio_id INT NOT NULL,
  nome VARCHAR(255) NOT NULL,
  telefone VARCHAR(50) NOT NULL,
  mensagem TEXT,
  criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (relatorio_id) REFERENCES relatorios(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS mensagens_chat (
  id INT AUTO_INCREMENT PRIMARY KEY,
  relatorio_id INT NOT NULL,
  autor VARCHAR(255) NOT NULL,
  texto TEXT NOT NULL,
  criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (relatorio_id) REFERENCES relatorios(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS participacoes_relatorio (
  id INT AUTO_INCREMENT PRIMARY KEY,
  relatorio_id INT NOT NULL,
  usuario_id INT,
  tipo_participacao VARCHAR(30) NOT NULL,
  criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (relatorio_id) REFERENCES relatorios(id) ON DELETE CASCADE,
  FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE
);
